Algoritmo "Antecessor e Sucessor"
Var
   n,a,s: inteiro


Inicio
       Escreval ("---------------------")
       Escreval ("Antecessor e Sucessor")
       Escreval ("---------------------")
       Escreva("Digite um número:")
       leia(n)
       a := n - 1
       s := n + 1
       Escreval ("O sucessor de ", n, " é igual a:",s)
       Escreval ("O antecessor de ",n, " é igual a:", a)


Fimalgoritmo