Algoritmo "Conversor de Fahrenheith p celsius"
Var
   F, C: real
Inicio
      Escreval ("-------------------------")
      Escreval ("CONVERSOR DE TEMPERATURA")
      Escreval ("-------------------------")
      Escreval ("Digite o valor da temperatura em celsius: ")
      leia (C)
      F := C * 1.8 + 32
      Escreva("Após a conversão, a temperatura em Fahrenheith é igual a: ", F)
      

Fimalgoritmo