Algoritmo "Média"

Var
   Pn, Sn, M: Real


Inicio
      Escreva ("Primeira nota: ")
      Leia (Pn)
      Escreva ("Segunda nota: ")
      Leia (Sn)
      M <- (Pn + Sn) / 2
      Se M >= 6 então
         Escreva ("Sua média foi ", M, " Pontos, meus parabéns, você foi aprovado :)")
      Senao
           Escreva ("Sua média foi ", M, " Pontos, você infelizmente foi reprovado.")
      Fimse



Fimalgoritmo