Algoritmo "funcoesvisualg"

Var
N: Caractere


Inicio
      Escreval ("Digite seu nome")
      Leia (N)
      Escreval ("o total de caracteres em seu nome é: ",Compr(N))
      Escreval ("Seu nome em maiúsculo fica: " ,Maiusc(N))
      Escreval ("Seu nome em minusculo fica: ",Minusc(N))
      Escreval ("A primeira letra do seu nome é: ",Copia(N, 1, 1))
      Escreval ("Seu nome tem letra A na posição: ", Pos("A", Maiusc(N)))

Fimalgoritmo