algoritmo "positivo, neutro ou negativo"
var
   n: inteiro
inicio
      //Obter número do usuário//
      Escreval("Digite um número: ")
      leia(n)
      //condições//
      Se (n>0)entao
         Escreval("O número digitado é positivo")
      senao
           se (n=0) entao
              escreval ("O número digitado é nulo (0)")
           senao
                Escreval("O número digitado é negativo")
           fimse
      fimse
fimalgoritmo