Algoritmo "ProcedimentoReferencia"

Var
X, Y: Inteiro
Procedimento Soma ( Var A, B : Inteiro)
Inicio
      A <- A + 1
      B <- B + 2
      Escreval ("Valor de A igual a: ", A)
      Escreval ("Valor de B igual a: ", B)
      Escreval ("Soma de A + B = ", A + B)
FimProcedimento


Inicio
X <- 4
Y <- 8
  Soma (X,Y)
  Escreval ("Valor de X igual a: ", X)
  Escreval ("Valor de Y igual a: ", Y)



Fimalgoritmo