Algoritmo "Quadrado e cubo"
Var
   n1, n2, q1, c2: real


Inicio
       Escreval ("------------------")
       Escreval (" QUADRADO E CUBO")
       Escreval ("------------------")
       Escreval ("Digite um valor:")
       leia (n1)
       Escreval ("Digite outro valor:")
       leia(n2)
       q1 := n1^2
       c2 := n2^3
       Escreval("O valor ",n1," elevado ao quadrado é igual a:",q1)
       Escreval("O valor ", n2," elevado ao cubo é igual a:",c2)


Fimalgoritmo